# Generated by Django 5.2 on 2025-04-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThumbnailFiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sha256_hash",
                    models.CharField(
                        blank=True, db_index=True, default=None, null=True, unique=True
                    ),
                ),
                (
                    "fqpn_filename",
                    models.CharField(
                        db_index=True, default=None, max_length=384, unique=True
                    ),
                ),
                ("small_thumb", models.BinaryField(default=b"", null=True)),
                ("medium_thumb", models.BinaryField(default=b"", null=True)),
                ("large_thumb", models.BinaryField(default=b"", null=True)),
            ],
            options={
                "verbose_name": "Image File Thumbnails Cache",
                "verbose_name_plural": "Image File Thumbnails Cache",
            },
        ),
    ]
