# Generated by Django 4.1.3 on 2022-11-25 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LargeThumb",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("Thumbnail", models.BinaryField(default=b"")),
                ("FileSize", models.BigIntegerField(default=-1)),
            ],
            options={
                "verbose_name": "Image File Large Thumbnail Cache",
                "verbose_name_plural": "Image File Large Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="MediumThumb",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("Thumbnail", models.BinaryField(default=b"")),
                ("FileSize", models.BigIntegerField(default=-1)),
            ],
            options={
                "verbose_name": "Image File Medium Thumbnail Cache",
                "verbose_name_plural": "Image File Medium Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="SmallThumb",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("Thumbnail", models.BinaryField(default=b"")),
                ("FileSize", models.BigIntegerField(default=-1)),
            ],
            options={
                "verbose_name": "Image File Small Thumbnail Cache",
                "verbose_name_plural": "Image File Small Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="Thumbnails_Archive",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "zipfilepath",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=384
                    ),
                ),
                (
                    "FilePath",
                    models.CharField(db_index=True, default=None, max_length=384),
                ),
                (
                    "FileName",
                    models.CharField(db_index=True, default=None, max_length=384),
                ),
                ("SmallThumb", models.BinaryField(default=b"")),
            ],
            options={
                "verbose_name": "Archive Thumbnails Cache",
                "verbose_name_plural": "Archive Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="Thumbnails_Archive_Pages",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("page", models.IntegerField(default=0)),
                ("FileSize", models.BigIntegerField(default=-1)),
                ("SmallThumb", models.BinaryField(default=b"")),
                ("MediumThumb", models.BinaryField(default=b"")),
                ("LargeThumb", models.BinaryField(default=b"")),
            ],
            options={
                "verbose_name": "Archive Pages Cache",
                "verbose_name_plural": "Archive Pages Cache",
            },
        ),
        migrations.CreateModel(
            name="Thumbnails_Files",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "FileName",
                    models.CharField(db_index=True, default=None, max_length=384),
                ),
                ("FileSize", models.BigIntegerField(default=-1)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "LargeThumb",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thumbnails.largethumb",
                    ),
                ),
                (
                    "MediumThumb",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thumbnails.mediumthumb",
                    ),
                ),
                (
                    "SmallThumb",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thumbnails.smallthumb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thumbnails Index for Files",
                "verbose_name_plural": "Thumbnails Index for Files",
            },
        ),
        migrations.CreateModel(
            name="Thumbnails_Dir",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "DirName",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=384
                    ),
                ),
                (
                    "FileName",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=384
                    ),
                ),
                ("FileSize", models.BigIntegerField(default=-1)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "Thumbnail",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thumbnails.smallthumb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Directory Thumbnails Cache",
                "verbose_name_plural": "Directory Thumbnails Cache",
            },
        ),
    ]
