# Generated by Django 4.1.3 on 2022-11-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnails_files",
            name="ignore",
            field=models.BooleanField(default=False),
        ),
    ]
