# Generated by Django 5.2.1 on 2025-05-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thumbnailfiles",
            name="fqpn_filename",
        ),
    ]
