# Generated by Django 5.1.5 on 2025-01-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnailfiles",
            name="sha256_hash",
            field=models.CharField(
                blank=True, db_index=True, default=None, null=True, unique=True
            ),
        ),
    ]
