# Generated by Django 5.2.1 on 2025-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0002_remove_thumbnailfiles_fqpn_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnailfiles",
            name="sha256_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
