# Generated by Django 5.1.5 on 2025-01-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0002_thumbnailfiles_sha256_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thumbnailfiles",
            name="fqpn_hash",
        ),
    ]
