# Generated by Django 4.1.3 on 2022-11-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0002_thumbnails_files_ignore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnails_files",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
    ]
