# Generated by Django 5.2.1 on 2025-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0003_alter_thumbnailfiles_sha256_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnailfiles",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
