# Generated by Django 4.1.3 on 2022-12-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0003_alter_thumbnails_files_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="largethumb",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="mediumthumb",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="smallthumb",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
    ]
