# Generated by Django 6.0a1 on 2025-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0004_alter_thumbnailfiles_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="thumbnailfiles",
            index=models.Index(
                condition=models.Q(("sha256_hash__isnull", False)),
                fields=["sha256_hash"],
                name="thumbnails_sha256_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="thumbnailfiles",
            index=models.Index(
                condition=models.Q(
                    ("small_thumb__isnull", False),
                    models.Q(("small_thumb", b""), _negated=True),
                ),
                fields=["sha256_hash"],
                name="thumbnails_has_small_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="thumbnailfiles",
            index=models.Index(
                condition=models.Q(
                    ("medium_thumb__isnull", False),
                    models.Q(("medium_thumb", b""), _negated=True),
                ),
                fields=["sha256_hash"],
                name="thumbnails_has_medium_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="thumbnailfiles",
            index=models.Index(
                condition=models.Q(
                    ("large_thumb__isnull", False),
                    models.Q(("large_thumb", b""), _negated=True),
                ),
                fields=["sha256_hash"],
                name="thumbnails_has_large_idx",
            ),
        ),
    ]
