"""Normalize "no thumbnail data" to NULL: convert b"" rows, index the NULL state, forbid b""."""

# Generated by Django 6.0.6 on 2026-07-04 15:48

from django.db import migrations, models

_BLOB_FIELDS = ("small_thumb", "medium_thumb", "large_thumb")


def _empty_blobs_to_null(apps, schema_editor) -> None:
    """
    Convert legacy b"" thumbnail blobs to NULL.

    NULL becomes the only representation of "no thumbnail data"; the
    thumbnails_no_empty_blobs constraint added later in this migration
    would reject existing b"" rows, so they are converted first.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor (unused)
    """
    thumbnail_files = apps.get_model("thumbnails", "ThumbnailFiles")
    for field in _BLOB_FIELDS:
        thumbnail_files.objects.filter(**{field: b""}).update(**{field: None})


def _null_blobs_to_empty(apps, schema_editor) -> None:
    """
    Restore NULL thumbnail blobs to the legacy b"" representation (reverse).

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor (unused)
    """
    thumbnail_files = apps.get_model("thumbnails", "ThumbnailFiles")
    for field in _BLOB_FIELDS:
        thumbnail_files.objects.filter(**{f"{field}__isnull": True}).update(**{field: b""})


class Migration(migrations.Migration):
    """AlterField defaults → RunPython b""→NULL → partial index → CHECK constraint."""

    dependencies = [
        ("thumbnails", "0005_thumbnailfiles_thumbnails_sha256_lookup_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnailfiles",
            name="large_thumb",
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="thumbnailfiles",
            name="medium_thumb",
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="thumbnailfiles",
            name="small_thumb",
            field=models.BinaryField(default=None, null=True),
        ),
        # Data conversion MUST precede AddConstraint: PostgreSQL validates
        # existing rows when the CHECK is added, and b"" rows would fail it.
        migrations.RunPython(_empty_blobs_to_null, _null_blobs_to_empty),
        migrations.AddIndex(
            model_name="thumbnailfiles",
            index=models.Index(condition=models.Q(("small_thumb__isnull", True)), fields=["id"], name="thumbnails_small_missing_idx"),
        ),
        migrations.AddConstraint(
            model_name="thumbnailfiles",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("small_thumb", b""), _negated=True),
                    models.Q(("medium_thumb", b""), _negated=True),
                    models.Q(("large_thumb", b""), _negated=True),
                ),
                name="thumbnails_no_empty_blobs",
            ),
        ),
    ]
