# Generated by Django 6.0.6 on 2026-07-05 00:43
#
# Index cleanup: sha256_lookup_idx duplicated the sha256_hash unique index;
# has_medium/has_large were never scanned (nothing queries medium/large-blob
# existence). See claude_docs/plans/fable_optimizations-2.md Opt 2b.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0006_null_missing_thumbnails"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="thumbnailfiles",
            name="thumbnails_sha256_lookup_idx",
        ),
        migrations.RemoveIndex(
            model_name="thumbnailfiles",
            name="thumbnails_has_medium_idx",
        ),
        migrations.RemoveIndex(
            model_name="thumbnailfiles",
            name="thumbnails_has_large_idx",
        ),
        # Drop the auto-created varchar_pattern_ops companion of the
        # sha256_hash unique index (213 MB, 0 scans ever — no LIKE/startswith
        # queries exist on any SHA column, grep-verified 2026-07-04). Django
        # creates these implicitly for unique CharFields on PostgreSQL and has
        # no declarative removal, hence RunSQL.
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS "thumbnails_thumbnailfiles_sha256_hash_770c4a7d_like";',
            reverse_sql=(
                'CREATE INDEX "thumbnails_thumbnailfiles_sha256_hash_770c4a7d_like" '
                'ON "thumbnails_thumbnailfiles" ("sha256_hash" varchar_pattern_ops);'
            ),
        ),
    ]
