"""Create UserPreferences for all existing users."""

# Generated by Django 6.0b1 on 2025-10-24 01:25

from __future__ import annotations

from django.db import migrations


def create_user_preferences(apps, schema_editor) -> None:
    """
    Create UserPreferences for all existing users who don't have them.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    User = apps.get_model("auth", "User")
    UserPreferences = apps.get_model("user_preferences", "UserPreferences")

    # Get all users who don't have preferences
    users_without_prefs = User.objects.filter(preferences__isnull=True)

    # Create preferences for each user
    preferences_to_create = [
        UserPreferences(user=user, show_duplicates=False) for user in users_without_prefs
    ]

    # Bulk create for efficiency
    UserPreferences.objects.bulk_create(preferences_to_create)

    print(f"Created preferences for {len(preferences_to_create)} existing users")


def reverse_create_user_preferences(apps, schema_editor) -> None:
    """
    Reverse migration - delete auto-created preferences.

    Args:
        apps: Django apps registry
        schema_editor: Database schema editor
    """
    # We don't need to do anything on reverse - preferences can remain
    pass


class Migration(migrations.Migration):
    """Migration to create preferences for existing users."""

    dependencies = [
        ("user_preferences", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            create_user_preferences, reverse_code=reverse_create_user_preferences
        ),
    ]
