# Generated by Django 6.1 on 2026-08-09 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_preferences", "0002_create_preferences_for_existing_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.DB_CASCADE, related_name="preferences", to=settings.AUTH_USER_MODEL),
        ),
    ]
