# Generated by Django 6.1 on 2026-08-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_preferences", "0003_alter_userpreferences_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="if_font_size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                help_text="Text size for the Interactive Fiction play view",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="if_text_width",
            field=models.CharField(
                choices=[("narrow", "Narrow"), ("medium", "Medium"), ("wide", "Wide")],
                default="medium",
                help_text="Text column width for the Interactive Fiction play view",
                max_length=10,
            ),
        ),
    ]
