# Generated by Django 2.0.5 on 2018-05-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('quickbbs', '0001_squashed_0019_auto_20171108_0155'), ('quickbbs', '0002_indexdata_is_image'), ('quickbbs', '0003_auto_20180104_0041'), ('quickbbs', '0004_auto_20180104_0043'), ('quickbbs', '0005_auto_20180105_2126'), ('quickbbs', '0006_indexdata_md5_hash_id'), ('quickbbs', '0007_auto_20180309_0637'), ('quickbbs', '0008_remove_indexdata_md5_hash_id'), ('quickbbs', '0009_indexdata_thumbnail_id'), ('quickbbs', '0010_auto_20180311_1641'), ('quickbbs', '0011_thumbnails_files_filename'), ('quickbbs', '0012_auto_20180314_1134'), ('quickbbs', '0013_auto_20180315_0956'), ('quickbbs', '0014_thumbnails_files_filesize'), ('quickbbs', '0015_delete_thumbnails_files'), ('quickbbs', '0016_thumbnails_files'), ('quickbbs', '0017_auto_20180315_2138'), ('quickbbs', '0018_auto_20180315_2147'), ('quickbbs', '0019_thumbnails_dirs'), ('quickbbs', '0020_auto_20180317_1303'), ('quickbbs', '0021_thumbnails_dirs_filesize'), ('quickbbs', '0022_auto_20180330_0146'), ('quickbbs', '0023_thumbnails_archives_page'), ('quickbbs', '0024_auto_20180407_0225'), ('quickbbs', '0025_auto_20180407_0233'), ('quickbbs', '0026_auto_20180408_1605'), ('quickbbs', '0027_auto_20180415_0301'), ('quickbbs', '0028_auto_20180417_0220'), ('quickbbs', '0029_auto_20180417_0223'), ('quickbbs', '0030_auto_20180418_0024')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=None, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnails_Archives',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('SmallThumb', models.BinaryField(default=b'')),
                ('MediumThumb', models.BinaryField(default=b'')),
                ('LargeThumb', models.BinaryField(default=b'')),
                ('FileName', models.CharField(db_index=True, default=None, max_length=512)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileSize', models.BigIntegerField(default=-1)),
                ('page', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnails_Files',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileName', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileSize', models.BigIntegerField(default=-1)),
                ('SmallThumb', models.BinaryField(default=b'')),
                ('MediumThumb', models.BinaryField(default=b'')),
                ('LargeThumb', models.BinaryField(default=b'')),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnails_Dirs',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=512)),
                ('SmallThumb', models.BinaryField(default=b'')),
                ('FileSize', models.BigIntegerField(default=-1)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='index_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastscan', models.FloatField(db_index=True)),
                ('lastmod', models.FloatField(db_index=True)),
                ('name', models.CharField(db_index=True, default=None, max_length=512)),
                ('sortname', models.CharField(db_index=True, default='', editable=False, max_length=512)),
                ('size', models.BigIntegerField(default=0)),
                ('numfiles', models.IntegerField(default=0)),
                ('numdirs', models.IntegerField(default=0)),
                ('fqpndirectory', models.CharField(db_index=True, default=0, max_length=512)),
                ('parent_dir_id', models.IntegerField(default=0)),
                ('is_dir', models.BooleanField(db_index=True, default=False)),
                ('is_pdf', models.BooleanField(db_index=True, default=False)),
                ('is_archive', models.BooleanField(db_index=True, default=False)),
                ('is_image', models.BooleanField(db_index=True, default=False)),
                ('ignore', models.BooleanField(db_index=True, default=False)),
                ('delete_pending', models.BooleanField(db_index=True, default=False)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
            ],
        ),
    ]
