# Generated by Django 5.2 on 2025-04-02 19:50

import django.db.models.deletion
import quickbbs.natsort_model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filetypes", "0001_initial"),
        ("thumbnails", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorites",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndexDirs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "fqpndirectory",
                    models.CharField(
                        blank=True, default="", max_length=384, unique=True
                    ),
                ),
                (
                    "dir_sha256",
                    models.CharField(
                        blank=True, db_index=True, default=None, null=True, unique=True
                    ),
                ),
                ("dir_name_md5", models.CharField(db_index=True, max_length=32)),
                (
                    "combined_md5",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("parent_dir_md5", models.CharField(db_index=True, max_length=32)),
                ("lastscan", models.FloatField(db_index=True, default=None)),
                ("lastmod", models.FloatField(db_index=True, default=None)),
                (
                    "name_sort",
                    quickbbs.natsort_model.NaturalSortField(
                        "fqpndirectory",
                        db_index=True,
                        default="",
                        editable=False,
                        max_length=384,
                    ),
                ),
                ("is_generic_icon", models.BooleanField(db_index=True, default=False)),
                ("ignore", models.BooleanField(db_index=True, default=False)),
                ("delete_pending", models.BooleanField(db_index=True, default=False)),
                ("small_thumb", models.BinaryField(default=b"")),
                (
                    "filetype",
                    models.ForeignKey(
                        default=".dir",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filetypes.filetypes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Directory Index",
                "verbose_name_plural": "Master Directory Index",
            },
        ),
        migrations.CreateModel(
            name="Owners",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "ownerdetails",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ownership",
                "verbose_name_plural": "Ownership",
            },
        ),
        migrations.CreateModel(
            name="IndexData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "file_sha256",
                    models.CharField(
                        blank=True, db_index=True, default=None, null=True, unique=True
                    ),
                ),
                (
                    "unique_sha256",
                    models.CharField(
                        blank=True, db_index=True, default=None, null=True, unique=True
                    ),
                ),
                ("lastscan", models.FloatField(db_index=True)),
                ("lastmod", models.FloatField(db_index=True)),
                ("name", models.CharField(db_index=True, default=None, max_length=384)),
                (
                    "name_sort",
                    quickbbs.natsort_model.NaturalSortField(
                        "name",
                        db_index=True,
                        default="",
                        editable=False,
                        max_length=384,
                    ),
                ),
                ("duration", models.DurationField(null=True)),
                ("size", models.BigIntegerField(default=0)),
                (
                    "fqpndirectory",
                    models.CharField(db_index=True, default=0, max_length=384),
                ),
                ("is_animated", models.BooleanField(db_index=True, default=False)),
                ("ignore", models.BooleanField(db_index=True, default=False)),
                ("delete_pending", models.BooleanField(db_index=True, default=False)),
                ("index_image", models.BooleanField(db_index=True, default=False)),
                ("is_generic_icon", models.BooleanField(default=False)),
                (
                    "filetype",
                    models.ForeignKey(
                        default=".none",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filetypes.filetypes",
                    ),
                ),
                (
                    "new_ftnail",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thumbnails.thumbnailfiles",
                    ),
                ),
                (
                    "parent_dir",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickbbs.indexdirs",
                    ),
                ),
                (
                    "ownership",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickbbs.owners",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Files Index",
                "verbose_name_plural": "Master Files Index",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "fqpndirectory"), name="unique name directory"
                    )
                ],
            },
        ),
    ]
