# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LastMod', models.DateField(db_index=True)),
                ('LastScan', models.DateField(db_index=True)),
                ('DirFQFN', models.CharField(db_index=True, default=None, max_length=512)),
                ('DirURL', models.CharField(db_index=True, default=None, max_length=512)),
                ('NumFiles', models.IntegerField(default=0)),
                ('NumDirs', models.IntegerField(default=0)),
                ('ParentDirID', models.IntegerField(db_index=True, default=0)),
                ('ThumbFQFN', models.CharField(db_index=True, default=None, max_length=512)),
                ('ThumbURL', models.CharField(db_index=True, default=None, max_length=512)),
                ('Ignore', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LastMod', models.DateField(db_index=True)),
                ('LastScan', models.DateField(db_index=True)),
                ('FilenameName', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileSize', models.IntegerField(default=0)),
                ('NumDirs', models.IntegerField(default=0)),
                ('ParentDirID', models.IntegerField(default=0)),
                ('ThumbFQFN', models.CharField(db_index=True, default=None, max_length=512)),
                ('ThumbURL', models.CharField(db_index=True, default=None, max_length=512)),
                ('IgnoreFile', models.BooleanField(db_index=True, default=False)),
                ('DeletePending', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
