# Generated by Django 4.1.3 on 2022-11-25 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filetypes", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cache_Tracking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DirName",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=384
                    ),
                ),
                ("lastscan", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Favorites",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thumbnails_Archives",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "zipfilepath",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=384
                    ),
                ),
                (
                    "FilePath",
                    models.CharField(db_index=True, default=None, max_length=384),
                ),
                (
                    "FileName",
                    models.CharField(db_index=True, default=None, max_length=384),
                ),
                ("page", models.IntegerField(default=0)),
                ("FileSize", models.BigIntegerField(default=-1)),
                ("SmallThumb", models.BinaryField(default=b"")),
                ("MediumThumb", models.BinaryField(default=b"")),
                ("LargeThumb", models.BinaryField(default=b"")),
            ],
            options={
                "verbose_name": "Archive Thumbnails Cache",
                "verbose_name_plural": "Archive Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="Thumbnails_Dirs",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "DirName",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=384
                    ),
                ),
                ("FileSize", models.BigIntegerField(default=-1)),
                (
                    "FilePath",
                    models.CharField(db_index=True, default=None, max_length=384),
                ),
                ("SmallThumb", models.BinaryField(default=b"")),
            ],
            options={
                "verbose_name": "Directory Thumbnails Cache",
                "verbose_name_plural": "Directory Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="Thumbnails_Files",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "FilePath",
                    models.CharField(db_index=True, default=None, max_length=384),
                ),
                (
                    "FileName",
                    models.CharField(db_index=True, default=None, max_length=384),
                ),
                ("FileSize", models.BigIntegerField(default=-1)),
                ("SmallThumb", models.BinaryField(default=b"")),
                ("MediumThumb", models.BinaryField(default=b"")),
                ("LargeThumb", models.BinaryField(default=b"")),
            ],
            options={
                "verbose_name": "Image File Thumbnails Cache",
                "verbose_name_plural": "Image File Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="Thumbnails_Large",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("Thumbnail", models.BinaryField(default=b"")),
                ("FileSize", models.BigIntegerField(default=-1)),
            ],
            options={
                "verbose_name": "Image File Large Thumbnail Cache",
                "verbose_name_plural": "Image File Large Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="Thumbnails_Medium",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("Thumbnail", models.BinaryField(default=b"")),
                ("FileSize", models.BigIntegerField(default=-1)),
            ],
            options={
                "verbose_name": "Image File Medium Thumbnail Cache",
                "verbose_name_plural": "Image File Medium Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="Thumbnails_Small",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("Thumbnail", models.BinaryField(default=b"")),
                ("FileSize", models.BigIntegerField(default=-1)),
            ],
            options={
                "verbose_name": "Image File Small Thumbnail Cache",
                "verbose_name_plural": "Image File Small Thumbnails Cache",
            },
        ),
        migrations.CreateModel(
            name="owners",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                (
                    "ownerdetails",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ownership",
                "verbose_name_plural": "Ownership",
            },
        ),
        migrations.CreateModel(
            name="index_data",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("lastscan", models.FloatField(db_index=True)),
                ("lastmod", models.FloatField(db_index=True)),
                ("name", models.CharField(db_index=True, default=None, max_length=384)),
                (
                    "sortname",
                    models.CharField(
                        db_index=True, default="", editable=False, max_length=384
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("numfiles", models.IntegerField(default=0)),
                ("numdirs", models.IntegerField(default=0)),
                ("count_subfiles", models.BigIntegerField(default=0)),
                (
                    "fqpndirectory",
                    models.CharField(db_index=True, default=0, max_length=384),
                ),
                ("parent_dir_id", models.IntegerField(default=0)),
                ("is_animated", models.BooleanField(db_index=True, default=False)),
                ("ignore", models.BooleanField(db_index=True, default=False)),
                ("delete_pending", models.BooleanField(db_index=True, default=False)),
                (
                    "archives",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickbbs.thumbnails_archives",
                    ),
                ),
                (
                    "directory",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickbbs.thumbnails_dirs",
                    ),
                ),
                (
                    "file_tnail",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickbbs.thumbnails_files",
                    ),
                ),
                (
                    "filetype",
                    models.ForeignKey(
                        default=".none",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filetypes.filetypes",
                    ),
                ),
                (
                    "ownership",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quickbbs.owners",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Index",
                "verbose_name_plural": "Master Index",
            },
        ),
    ]
