# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'quickbbs', '0001_initial'), (b'quickbbs', '0002_auto_20171102_0127'), (b'quickbbs', '0003_auto_20171102_0129'), (b'quickbbs', '0004_auto_20171102_0133'), (b'quickbbs', '0005_auto_20171103_0237'), (b'quickbbs', '0006_auto_20171104_0123'), (b'quickbbs', '0007_auto_20171104_0135'), (b'quickbbs', '0008_auto_20171104_0138'), (b'quickbbs', '0009_auto_20171104_0140'), (b'quickbbs', '0010_auto_20171104_0140'), (b'quickbbs', '0011_auto_20171105_1233'), (b'quickbbs', '0012_auto_20171107_1013'), (b'quickbbs', '0013_auto_20171107_1121'), (b'quickbbs', '0014_filedata_sortfilename'), (b'quickbbs', '0015_auto_20171107_1413'), (b'quickbbs', '0016_auto_20171107_1414'), (b'quickbbs', '0017_auto_20171107_1415'), (b'quickbbs', '0018_auto_20171108_0149'), (b'quickbbs', '0019_auto_20171108_0155')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LastScan', models.FloatField(db_index=True)),
                ('LastMod', models.FloatField(db_index=True)),
                ('Name', models.CharField(db_index=True, default=None, max_length=512)),
                ('SortName', models.CharField(db_index=True, default='', editable=False, max_length=512)),
                ('Size', models.IntegerField(default=0)),
                ('FQPNDirectory', models.CharField(db_index=True, default=0, max_length=512)),
                ('ParentDirID', models.IntegerField(default=0)),
                ('is_dir', models.BooleanField(db_index=True, default=False)),
                ('is_pdf', models.BooleanField(db_index=True, default=False)),
                ('is_archive', models.BooleanField(db_index=True, default=False)),
                ('Ignore', models.BooleanField(default=False)),
                ('DeletePending', models.BooleanField(default=False)),
                ('NumDirs', models.IntegerField(default=0)),
                ('NumFiles', models.IntegerField(default=0)),
            ],
        ),
    ]
