# Generated by Django 3.2 on 2021-05-02 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnails_Large',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('Thumbnail', models.BinaryField(default=b'')),
            ],
            options={
                'verbose_name': 'Image File Large Thumbnail Cache',
                'verbose_name_plural': 'Image File Large Thumbnails Cache',
            },
        ),
        migrations.CreateModel(
            name='Thumbnails_Medium',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('Thumbnail', models.BinaryField(default=b'')),
            ],
            options={
                'verbose_name': 'Image File Medium Thumbnail Cache',
                'verbose_name_plural': 'Image File Medium Thumbnails Cache',
            },
        ),
        migrations.CreateModel(
            name='Thumbnails_Small',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('Thumbnail', models.BinaryField(default=b'')),
            ],
            options={
                'verbose_name': 'Image File Small Thumbnail Cache',
                'verbose_name_plural': 'Image File Small Thumbnails Cache',
            },
        ),
        migrations.AlterField(
            model_name='favorites',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='filetypes',
            name='icon_filename',
            field=models.CharField(blank=True, db_index=True, default='', max_length=384),
        ),
        migrations.AlterField(
            model_name='index_data',
            name='archives',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.thumbnails_archives'),
        ),
        migrations.AlterField(
            model_name='index_data',
            name='directory',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.thumbnails_dirs'),
        ),
        migrations.AlterField(
            model_name='index_data',
            name='file_tnail',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.thumbnails_files'),
        ),
        migrations.AlterField(
            model_name='index_data',
            name='ownership',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.owners'),
        ),
        migrations.AlterField(
            model_name='index_data',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnails_archives',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnails_archives',
            name='zipfilepath',
            field=models.CharField(blank=True, db_index=True, default='', max_length=384),
        ),
        migrations.AlterField(
            model_name='thumbnails_dirs',
            name='DirName',
            field=models.CharField(blank=True, db_index=True, default='', max_length=384),
        ),
        migrations.AlterField(
            model_name='thumbnails_dirs',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnails_files',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
