# Generated by Django 2.2.4 on 2019-09-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetypes',
            name='is_movie',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
