# Generated by Django 4.1.3 on 2022-11-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cache_Tracking",
        ),
    ]
