# Generated by Django 5.2 on 2025-04-02 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0001_initial"),
        ("thumbnails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdata",
            name="new_ftnail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="thumbnails.thumbnailfiles",
            ),
        ),
    ]
