# Generated by Django 5.2 on 2025-04-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0002_alter_indexdata_new_ftnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdata",
            name="file_sha256",
            field=models.CharField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
