# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0002_indexdata_is_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='indexdata',
            name='LargeThumb',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='indexdata',
            name='MediumThumb',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='indexdata',
            name='SmallThumb',
            field=models.BinaryField(default=b''),
        ),
    ]
