# Generated by Django 3.2.3 on 2021-05-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0003_auto_20210501_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache_Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DirName', models.CharField(blank=True, db_index=True, default='', max_length=384)),
                ('lastscan', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='filetypes',
            options={'verbose_name': 'File Type', 'verbose_name_plural': 'File Types'},
        ),
    ]
