# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0003_auto_20180104_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdata',
            name='LargeThumb',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='MediumThumb',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='SmallThumb',
            field=models.BinaryField(),
        ),
    ]
