# Generated by Django 5.2 on 2025-04-04 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0003_alter_indexdata_file_sha256"),
        ("thumbnails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdata",
            name="new_ftnail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="thumbnails.thumbnailfiles",
            ),
        ),
    ]
