# Generated by Django 4.1.3 on 2022-12-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0004_alter_largethumb_uuid_alter_mediumthumb_uuid_and_more"),
        ("quickbbs", "0003_index_data_unified_thumb"),
    ]

    operations = [
        migrations.AddField(
            model_name="index_data",
            name="unified_dirs",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="thumbnails.thumbnails_dir",
            ),
        ),
    ]
