# Generated by Django 5.2 on 2025-04-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0004_alter_indexdata_new_ftnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexdirs",
            name="file_links",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quickbbs.indexdata",
            ),
        ),
    ]
