# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0005_auto_20180105_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdata',
            name='md5_hash_id',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
