# Generated by Django 5.2 on 2025-04-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0005_indexdirs_file_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexdirs",
            name="dir_name_md5",
        ),
    ]
