# Generated by Django 5.2.1 on 2025-05-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0001_initial"),
        ("quickbbs", "0006_remove_indexdirs_dir_name_md5"),
        ("thumbnails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexdata",
            name="dir_sha256",
            field=models.CharField(
                blank=True, db_index=True, default=None, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="indexdata",
            name="filetype",
            field=models.ForeignKey(
                default=".none",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_filetype_data",
                to="filetypes.filetypes",
            ),
        ),
        migrations.AlterField(
            model_name="indexdata",
            name="new_ftnail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="IndexData",
                to="thumbnails.thumbnailfiles",
            ),
        ),
        migrations.AlterField(
            model_name="indexdirs",
            name="file_links",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="file_links",
                to="quickbbs.indexdata",
            ),
        ),
        migrations.AlterField(
            model_name="indexdirs",
            name="filetype",
            field=models.ForeignKey(
                default=".dir",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dirs_filetype_data",
                to="filetypes.filetypes",
            ),
        ),
    ]
