# Generated by Django 5.2.1 on 2025-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0007_indexdata_dir_sha256_alter_indexdata_filetype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexdirs",
            name="dir_parent_sha256",
            field=models.CharField(db_index=True, default=None, null=True),
        ),
    ]
