# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0007_auto_20180309_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdata',
            name='md5_hash_id',
        ),
    ]
