# Generated by Django 5.2.1 on 2025-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0008_indexdirs_dir_parent_sha256"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indexdirs",
            old_name="dir_sha256",
            new_name="dir_fqpn_sha256",
        ),
        migrations.RemoveField(
            model_name="indexdirs",
            name="ignore",
        ),
        migrations.AddField(
            model_name="indexdirs",
            name="dirname_sha256",
            field=models.CharField(
                blank=True, db_index=True, default=None, null=True, unique=True
            ),
        ),
    ]
