# Generated by Django 5.2.1 on 2025-05-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0009_rename_dir_sha256_indexdirs_dir_fqpn_sha256_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexdirs",
            name="dirname_sha256",
        ),
    ]
