# Generated by Django 5.2.1 on 2025-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0010_remove_indexdirs_dirname_sha256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdata",
            name="dir_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="indexdata",
            name="file_sha256",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="indexdata",
            name="unique_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="indexdirs",
            name="dir_fqpn_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="indexdirs",
            name="dir_parent_sha256",
            field=models.CharField(
                db_index=True, default=None, max_length=64, null=True
            ),
        ),
    ]
