# Generated by Django 5.2.1 on 2025-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0011_alter_indexdata_dir_sha256_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdirs",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
