# Generated by Django 5.2.1 on 2025-06-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0012_alter_indexdirs_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexdirs",
            name="file_links",
        ),
        migrations.AddField(
            model_name="indexdirs",
            name="file_links",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="file_links",
                to="quickbbs.indexdata",
            ),
        ),
    ]
