# Generated by Django 5.2.1 on 2025-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0013_remove_indexdirs_file_links_indexdirs_file_links"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indexdata",
            old_name="index_image",
            new_name="cover_image",
        ),
        migrations.AlterField(
            model_name="indexdirs",
            name="file_links",
            field=models.ManyToManyField(
                default=None, related_name="file_links", to="quickbbs.indexdata"
            ),
        ),
    ]
