# Generated by Django 5.2.1 on 2025-06-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0014_rename_index_image_indexdata_cover_image_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="indexdata",
            name="unique name directory",
        ),
        migrations.RemoveField(
            model_name="indexdata",
            name="fqpndirectory",
        ),
    ]
