# Generated by Django 5.2.1 on 2025-06-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0015_remove_indexdata_unique_name_directory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indexdata",
            old_name="parent_dir",
            new_name="home_directory",
        ),
    ]
