# Generated by Django 5.2.1 on 2025-06-07 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0016_rename_parent_dir_indexdata_home_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdata",
            name="home_directory",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="IndexData_entries",
                to="quickbbs.indexdirs",
            ),
        ),
    ]
