# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0017_auto_20180315_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnails_files',
            name='DeletePending',
        ),
        migrations.RemoveField(
            model_name='thumbnails_files',
            name='Flag_For_Regeneration',
        ),
    ]
