# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0017_auto_20171107_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LastScan', models.FloatField(db_index=True)),
                ('LastMod', models.FloatField(db_index=True)),
                ('Name', models.CharField(db_index=True, default=None, max_length=512)),
                ('SortName', models.CharField(db_index=True, default='', editable=False, max_length=512)),
                ('Size', models.IntegerField(default=0)),
                ('FQPNDirectory', models.CharField(db_index=True, default=0, max_length=512)),
                ('ParentDirID', models.IntegerField(default=0)),
                ('is_dir', models.BooleanField(db_index=True, default=False)),
                ('is_pdf', models.BooleanField(db_index=True, default=False)),
                ('is_archive', models.BooleanField(db_index=True, default=False)),
                ('Ignore', models.BooleanField(default=False)),
                ('DeletePending', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DirData',
        ),
        migrations.DeleteModel(
            name='FileData',
        ),
    ]
