# Generated by Django 5.2.3 on 2025-06-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0017_alter_indexdata_home_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexdirs",
            name="thumbnail",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dir_thumbnail",
                to="quickbbs.indexdata",
            ),
        ),
    ]
