# Generated by Django 5.2.3 on 2025-06-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0018_indexdirs_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexdirs",
            name="small_thumb",
        ),
    ]
