# Generated by Django 5.2.3 on 2025-06-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0020_remove_indexdata_uuid_remove_indexdirs_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexdirs",
            name="combined_md5",
        ),
        migrations.RemoveField(
            model_name="indexdirs",
            name="parent_dir_md5",
        ),
    ]
