# Generated by Django 5.2.3 on 2025-06-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0021_remove_indexdirs_combined_md5_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexdata",
            name="duration",
        ),
    ]
