# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-30 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0021_thumbnails_dirs_filesize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnails_archives',
            name='DeletePending',
        ),
        migrations.RemoveField(
            model_name='thumbnails_archives',
            name='Flag_For_Regeneration',
        ),
        migrations.RemoveField(
            model_name='thumbnails_archives',
            name='UsageCount',
        ),
        migrations.AddField(
            model_name='thumbnails_archives',
            name='FileName',
            field=models.CharField(db_index=True, default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='thumbnails_archives',
            name='FilePath',
            field=models.CharField(db_index=True, default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='thumbnails_archives',
            name='FileSize',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='thumbnails_archives',
            name='LargeThumb',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='thumbnails_archives',
            name='MediumThumb',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='thumbnails_archives',
            name='SmallThumb',
            field=models.BinaryField(default=b''),
        ),
    ]
