# Generated by Django 5.2.3 on 2025-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0022_remove_indexdata_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexdata",
            name="duration",
            field=models.BigIntegerField(null=True),
        ),
    ]
