# Generated by Django 5.2.3 on 2025-06-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0023_indexdata_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexdirs",
            name="parent_directory",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_dir",
                to="quickbbs.indexdirs",
            ),
        ),
        migrations.AlterField(
            model_name="indexdirs",
            name="thumbnail",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dir_thumbnail",
                to="quickbbs.indexdata",
            ),
        ),
    ]
