# Generated by Django 5.2.3 on 2025-06-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0024_indexdirs_parent_directory_alter_indexdirs_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexdirs",
            name="dir_parent_sha256",
        ),
    ]
