# Generated by Django 5.2.4 on 2025-07-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0025_remove_indexdirs_dir_parent_sha256"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexdata",
            name="dir_sha256",
        ),
    ]
