# Generated by Django 5.2.4 on 2025-07-04 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0026_remove_indexdata_dir_sha256"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexdata",
            name="virtual_directory",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Virtual_IndexData",
                to="quickbbs.indexdirs",
            ),
        ),
    ]
