# Generated by Django 5.2.4 on 2025-07-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0027_indexdata_virtual_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdirs",
            name="thumbnail",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dir_thumbnail",
                to="quickbbs.indexdata",
            ),
        ),
    ]
