# Generated by Django 6.0a1 on 2025-09-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0002_filetypes_thumbnail"),
        ("quickbbs", "0028_alter_indexdirs_thumbnail"),
        ("thumbnails", "0004_alter_thumbnailfiles_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="indexdata",
            index=models.Index(
                fields=["home_directory", "delete_pending"],
                name="quickbbs_in_home_di_0f48e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indexdata",
            index=models.Index(
                fields=["file_sha256", "delete_pending"],
                name="quickbbs_in_file_sh_4a2d4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indexdata",
            index=models.Index(fields=["name"], name="quickbbs_indexdata_name_idx"),
        ),
        migrations.AddIndex(
            model_name="indexdirs",
            index=models.Index(
                fields=["parent_directory", "delete_pending"],
                name="quickbbs_in_parent__d3b95d_idx",
            ),
        ),
    ]
