# Generated by Django 6.0a1 on 2025-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0029_indexdata_quickbbs_in_home_di_0f48e7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdata",
            name="is_generic_icon",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="indexdirs",
            name="fqpndirectory",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=384, unique=True
            ),
        ),
    ]
