# Generated by Django 6.0a1 on 2025-09-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0002_filetypes_thumbnail"),
        ("quickbbs", "0030_alter_indexdata_is_generic_icon_and_more"),
        ("thumbnails", "0005_thumbnailfiles_thumbnails_sha256_lookup_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="indexdata",
            index=models.Index(
                fields=["unique_sha256", "delete_pending"],
                name="quickbbs_in_unique__5a24e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indexdirs",
            index=models.Index(
                fields=["dir_fqpn_sha256", "delete_pending"],
                name="quickbbs_in_dir_fqp_9df693_idx",
            ),
        ),
    ]
