# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0030_auto_20180418_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails_archives',
            name='zipfilepath',
            field=models.CharField(db_index=True, default=None, max_length=512, null=True),
        ),
    ]
