# Generated by Django 6.0a1 on 2025-10-22 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0031_indexdata_quickbbs_in_unique__5a24e6_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdata",
            name="home_directory",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="IndexData_entries", to="quickbbs.indexdirs"
            ),
        ),
        migrations.AlterField(
            model_name="indexdata",
            name="virtual_directory",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="Virtual_IndexData", to="quickbbs.indexdirs"
            ),
        ),
        migrations.AlterField(
            model_name="indexdirs",
            name="thumbnail",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dir_thumbnail", to="quickbbs.indexdata"
            ),
        ),
    ]
