# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-25 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickbbs', '0031_thumbnails_archives_zipfilepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=None, editable=False, null=True)),
                ('ownerdetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
