# Generated by Django 6.0b1 on 2025-11-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0003_filetypes_filetypes_thumbnailable_idx_and_more"),
        ("quickbbs", "0032_alter_indexdata_home_directory_and_more"),
        ("thumbnails", "0005_thumbnailfiles_thumbnails_sha256_lookup_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="indexdata",
            index=models.Index(fields=["name", "delete_pending"], name="indexdata_name_delete_idx"),
        ),
        migrations.AddIndex(
            model_name="indexdata",
            index=models.Index(fields=["filetype", "delete_pending"], name="indexdata_filetype_delete_idx"),
        ),
    ]
