# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-25 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0032_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='ownerdetails',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
