# Generated by Django 6.0b1 on 2025-11-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0003_filetypes_filetypes_thumbnailable_idx_and_more"),
        ("quickbbs", "0033_indexdata_indexdata_name_delete_idx_and_more"),
        ("thumbnails", "0005_thumbnailfiles_thumbnails_sha256_lookup_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="indexdata",
            index=models.Index(condition=models.Q(("new_ftnail__isnull", True)), fields=["file_sha256"], name="indexdata_sha256_unlinked_idx"),
        ),
        migrations.AddIndex(
            model_name="indexdata",
            index=models.Index(fields=["home_directory", "filetype", "delete_pending"], name="indexdata_home_type_delete_idx"),
        ),
    ]
