# Generated by Django 6.0b1 on 2025-11-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0035_rename_indexdirs_to_directoryindex"),
    ]

    operations = [
        # Rename the model from IndexData to FileIndex
        migrations.RenameModel(
            old_name="IndexData",
            new_name="FileIndex",
        ),
        # Rename database indexes to match new naming convention
        migrations.RenameIndex(
            model_name="fileindex",
            old_name="quickbbs_indexdata_name_idx",
            new_name="quickbbs_fileindex_name_idx",
        ),
        migrations.RenameIndex(
            model_name="fileindex",
            old_name="indexdata_name_delete_idx",
            new_name="fileindex_name_delete_idx",
        ),
        migrations.RenameIndex(
            model_name="fileindex",
            old_name="indexdata_filetype_delete_idx",
            new_name="fileindex_filetype_delete_idx",
        ),
        migrations.RenameIndex(
            model_name="fileindex",
            old_name="indexdata_sha256_unlinked_idx",
            new_name="fileindex_sha256_unlinked_idx",
        ),
        migrations.RenameIndex(
            model_name="fileindex",
            old_name="indexdata_home_type_delete_idx",
            new_name="fileindex_home_type_delete_idx",
        ),
    ]
