# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0035_index_data_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_data',
            name='file_tnail',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.Thumbnails_Files'),
        ),
    ]
