# Generated by Django 6.0b1 on 2025-11-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0036_rename_indexdata_to_fileindex"),
        ("thumbnails", "0005_thumbnailfiles_thumbnails_sha256_lookup_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="directoryindex",
            new_name="quickbbs_di_parent__6300e9_idx",
            old_name="quickbbs_in_parent__d3b95d_idx",
        ),
        migrations.RenameIndex(
            model_name="directoryindex",
            new_name="quickbbs_di_dir_fqp_625c9d_idx",
            old_name="quickbbs_in_dir_fqp_9df693_idx",
        ),
        migrations.RenameIndex(
            model_name="fileindex",
            new_name="quickbbs_fi_home_di_d5bcfe_idx",
            old_name="quickbbs_in_home_di_0f48e7_idx",
        ),
        migrations.RenameIndex(
            model_name="fileindex",
            new_name="quickbbs_fi_file_sh_c6317a_idx",
            old_name="quickbbs_in_file_sh_4a2d4f_idx",
        ),
        migrations.RenameIndex(
            model_name="fileindex",
            new_name="quickbbs_fi_unique__7ec993_idx",
            old_name="quickbbs_in_unique__5a24e6_idx",
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="home_directory",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="FileIndex_entries", to="quickbbs.directoryindex"
            ),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="new_ftnail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="FileIndex",
                to="thumbnails.thumbnailfiles",
            ),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="virtual_directory",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="Virtual_FileIndex", to="quickbbs.directoryindex"
            ),
        ),
    ]
