# Generated by Django 6.0.1 on 2026-01-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0037_rename_quickbbs_in_parent__d3b95d_idx_quickbbs_di_parent__6300e9_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryindex",
            name="dir_fqpn_sha256",
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="directoryindex",
            name="is_generic_icon",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="file_sha256",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="is_generic_icon",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="name",
            field=models.CharField(default=None, max_length=384),
        ),
    ]
