# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-02 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0037_index_data_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails_dirs',
            name='DirName',
            field=models.CharField(db_index=True, default=None, max_length=512, null=True),
        ),
    ]
