# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-12 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0038_thumbnails_dirs_dirname'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails_files',
            name='is_image',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='thumbnails_files',
            name='is_pdf',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
