# Generated by Django 6.0.6 on 2026-07-05 00:43
#
# Index cleanup + trigram search indexes.
# See claude_docs/plans/fable_optimizations-2.md (Opts 1, 2a, 2c) for the
# pg_stat_user_indexes / EXPLAIN evidence behind every removal.

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models

import quickbbs.natsort_model


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0004_alter_filetypes_filetype_alter_filetypes_generic_and_more"),
        ("quickbbs", "0038_alter_directoryindex_dir_fqpn_sha256_and_more"),
        ("thumbnails", "0007_remove_thumbnailfiles_thumbnails_sha256_lookup_idx_and_more"),
    ]

    operations = [
        # pg_trgm provides the gin_trgm_ops operator class used by the two
        # GinIndex operations below. Requires a role that may CREATE EXTENSION.
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name="fileindex",
            name="quickbbs_fi_home_di_d5bcfe_idx",
        ),
        migrations.RemoveIndex(
            model_name="fileindex",
            name="quickbbs_fi_unique__7ec993_idx",
        ),
        migrations.RemoveIndex(
            model_name="fileindex",
            name="fileindex_name_delete_idx",
        ),
        migrations.AlterField(
            model_name="directoryindex",
            name="delete_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="directoryindex",
            name="filetype",
            field=models.ForeignKey(
                db_index=False,
                default=".dir",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dirs_filetype_data",
                to="filetypes.filetypes",
            ),
        ),
        migrations.AlterField(
            model_name="directoryindex",
            name="lastmod",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="directoryindex",
            name="lastscan",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="directoryindex",
            name="name_sort",
            field=quickbbs.natsort_model.NaturalSortField("fqpndirectory", db_index=False, default="", editable=False, max_length=384),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="cover_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="delete_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="filetype",
            field=models.ForeignKey(
                db_index=False,
                default=".none",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_filetype_data",
                to="filetypes.filetypes",
            ),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="ignore",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="is_animated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="lastmod",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="lastscan",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="name_sort",
            field=quickbbs.natsort_model.NaturalSortField("name", db_index=False, default="", editable=False, max_length=384),
        ),
        migrations.AddIndex(
            model_name="directoryindex",
            index=django.contrib.postgres.indexes.GinIndex(fields=["fqpndirectory"], name="directoryindex_fqpn_trgm_idx", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="fileindex",
            index=models.Index(condition=models.Q(("delete_pending", True)), fields=["id"], name="fileindex_delete_pending_idx"),
        ),
        migrations.AddIndex(
            model_name="fileindex",
            index=django.contrib.postgres.indexes.GinIndex(fields=["name"], name="fileindex_name_trgm_idx", opclasses=["gin_trgm_ops"]),
        ),
        # Drop the auto-created varchar_pattern_ops companion of the
        # unique_sha256 unique index (247 MB, no LIKE/startswith queries exist
        # on any SHA column — grep-verified 2026-07-04). Django creates these
        # implicitly for unique CharFields on PostgreSQL and has no declarative
        # removal, hence RunSQL. Equality lookups use the unique index.
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS "quickbbs_indexdata_unique_sha256_07cafed8_like";',
            reverse_sql=(
                'CREATE INDEX "quickbbs_indexdata_unique_sha256_07cafed8_like" ' 'ON "quickbbs_fileindex" ("unique_sha256" varchar_pattern_ops);'
            ),
        ),
    ]
