# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0039_auto_20180512_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='filetypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileext', models.CharField(db_index=True, max_length=10, unique=True)),
                ('filesize', models.BigIntegerField(default=-1)),
                ('filename', models.CharField(db_index=True, default=None, max_length=512)),
                ('htmlcolor', models.CharField(max_length=7)),
                ('imageformat', models.BooleanField(db_index=True, default=False)),
                ('textformat', models.BooleanField(db_index=True, default=False)),
                ('smallthumb', models.BinaryField(default=b'')),
                ('largethumb', models.BinaryField(default=b'')),
            ],
        ),
    ]
