# Generated by Django 6.0.6 on 2026-07-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0039_remove_fileindex_quickbbs_fi_home_di_d5bcfe_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directoryindex",
            name="file_links",
        ),
    ]
