# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0040_filetypes'),
#        ('quickbbs', '0001_squashed_0040_filetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetypes',
            name='use_generic_icon',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
