# Generated by Django 6.0.7 on 2026-07-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0040_remove_directoryindex_file_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryindex",
            name="cache_invalidated",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="directoryindex",
            name="cache_lastscan",
            field=models.FloatField(default=0),
        ),
    ]
