# Generated by Django 6.1 on 2026-08-09 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0004_alter_filetypes_filetype_alter_filetypes_generic_and_more"),
        ("quickbbs", "0041_directoryindex_cache_invalidated_and_more"),
        ("thumbnails", "0007_remove_thumbnailfiles_thumbnails_sha256_lookup_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryindex",
            name="filetype",
            field=models.ForeignKey(
                db_index=False,
                default=".dir",
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="dirs_filetype_data",
                to="filetypes.filetypes",
            ),
        ),
        migrations.AlterField(
            model_name="directoryindex",
            name="parent_directory",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name="parent_dir", to="quickbbs.directoryindex"
            ),
        ),
        migrations.AlterField(
            model_name="directoryindex",
            name="thumbnail",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name="dir_thumbnail", to="quickbbs.fileindex"
            ),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="filetype",
            field=models.ForeignKey(
                db_index=False,
                default=".none",
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="file_filetype_data",
                to="filetypes.filetypes",
            ),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="home_directory",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DB_SET_NULL,
                related_name="FileIndex_entries",
                to="quickbbs.directoryindex",
            ),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="new_ftnail",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DB_SET_NULL,
                related_name="FileIndex",
                to="thumbnails.thumbnailfiles",
            ),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="ownership",
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to="quickbbs.owners"),
        ),
        migrations.AlterField(
            model_name="fileindex",
            name="virtual_directory",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DB_SET_NULL,
                related_name="Virtual_FileIndex",
                to="quickbbs.directoryindex",
            ),
        ),
        migrations.AlterField(
            model_name="owners",
            name="ownerdetails",
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DB_CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
