# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-16 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0041_filetypes_use_generic_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetypes',
            name='filename',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='filetypes',
            name='htmlcolor',
            field=models.CharField(default='000000', max_length=7),
        ),
    ]
