# Generated by Django 6.1 on 2026-08-17 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickbbs", "0042_alter_directoryindex_filetype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "directory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="favorited_by",
                        to="quickbbs.directoryindex",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, related_name="favorited_by", to="quickbbs.fileindex"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="favorites", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
            },
        ),
        migrations.DeleteModel(
            name="Favorites",
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(fields=["user", "-created"], name="quickbbs_fa_user_id_456b99_idx"),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.CheckConstraint(
                condition=models.Q(("file__isnull", False), ("directory__isnull", False), _connector="XOR"), name="favorite_exactly_one_target"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("file__isnull", False)), fields=("user", "file"), name="unique_user_file_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("directory__isnull", False)), fields=("user", "directory"), name="unique_user_directory_favorite"
            ),
        ),
    ]
