# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-16 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0042_auto_20180516_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetypes',
            name='archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
