# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0043_filetypes_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetypes',
            options={'verbose_name': 'File Type', 'verbose_name_plural': 'File Types'},
        ),
        migrations.AlterModelOptions(
            name='index_data',
            options={'verbose_name': 'Master Index', 'verbose_name_plural': 'Master Index'},
        ),
        migrations.AlterModelOptions(
            name='owners',
            options={'verbose_name': 'Ownership', 'verbose_name_plural': 'Ownership'},
        ),
        migrations.AlterModelOptions(
            name='thumbnails_archives',
            options={'verbose_name': 'Archive Thumbnails Cache', 'verbose_name_plural': 'Archive Thumbnails Cache'},
        ),
        migrations.AlterModelOptions(
            name='thumbnails_dirs',
            options={'verbose_name': 'Directory Thumbnails Cache', 'verbose_name_plural': 'Directory Thumbnails Cache'},
        ),
        migrations.AlterModelOptions(
            name='thumbnails_files',
            options={'verbose_name': 'Image File Thumbnails Cache', 'verbose_name_plural': 'Image File Thumbnails Cache'},
        ),
        migrations.AddField(
            model_name='index_data',
            name='count_subfiles',
            field=models.BigIntegerField(default=0),
        ),
    ]
