# Generated by Django 2.1.4 on 2018-12-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0044_auto_20180519_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetypes',
            old_name='htmlcolor',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='filetypes',
            old_name='use_generic_icon',
            new_name='generic',
        ),
        migrations.RemoveField(
            model_name='filetypes',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='filetypes',
            name='filesize',
        ),
        migrations.RemoveField(
            model_name='filetypes',
            name='imageformat',
        ),
        migrations.RemoveField(
            model_name='filetypes',
            name='largethumb',
        ),
        migrations.RemoveField(
            model_name='filetypes',
            name='smallthumb',
        ),
        migrations.RemoveField(
            model_name='filetypes',
            name='textformat',
        ),
        migrations.AddField(
            model_name='filetypes',
            name='filetype',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
