# Generated by Django 2.1.4 on 2018-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0045_auto_20181204_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_data',
            name='file_ext',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True),
        ),
    ]
