# Generated by Django 2.1.4 on 2018-12-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0047_auto_20181205_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetypes',
            name='filename',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True),
        ),
    ]
