# Generated by Django 2.1.4 on 2018-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0048_auto_20181205_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetypes',
            old_name='filename',
            new_name='icon_filename',
        ),
        migrations.RemoveField(
            model_name='filetypes',
            name='id',
        ),
        migrations.AlterField(
            model_name='filetypes',
            name='fileext',
            field=models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
