# Generated by Django 2.1.4 on 2018-12-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0049_auto_20181214_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetypes',
            options={},
        ),
        migrations.AddField(
            model_name='index_data',
            name='filetype',
            field=models.ForeignKey(default='.none', on_delete=django.db.models.deletion.CASCADE, to='quickbbs.filetypes'),
        ),
    ]
