# Generated by Django 2.1.4 on 2018-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0051_filetypes_is_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetypes',
            name='is_archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
