# Generated by Django 2.1.4 on 2018-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0052_filetypes_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetypes',
            name='is_pdf',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
