# Generated by Django 2.1.4 on 2018-12-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0053_filetypes_is_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_data',
            name='is_animated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
