# Generated by Django 2.1.4 on 2018-12-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0054_index_data_is_animated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_data',
            name='file_ext',
        ),
    ]
