# Generated by Django 5.1 on 2024-08-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fs_Cache_Tracking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Dir_md5_hdigest",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("DirName", models.CharField(blank=True, default="", max_length=384)),
                ("lastscan", models.FloatField()),
            ],
        ),
    ]
