# Generated by Django 5.2.1 on 2025-05-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CacheWatcher", "0002_fs_cache_tracking_directory_sha256"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fs_cache_tracking",
            name="Dir_md5_hdigest",
        ),
    ]
