# Generated by Django 5.2.1 on 2025-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CacheWatcher", "0003_remove_fs_cache_tracking_dir_md5_hdigest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fs_cache_tracking",
            name="directory_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
