# Generated by Django 5.2.1 on 2025-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CacheWatcher", "0004_alter_fs_cache_tracking_directory_sha256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fs_cache_tracking",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
