# Generated by Django 5.2.1 on 2025-05-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CacheWatcher", "0005_alter_fs_cache_tracking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fs_cache_tracking",
            name="lastscan",
            field=models.FloatField(blank=True, default=""),
        ),
    ]
