# Generated by Django 5.2.1 on 2025-05-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CacheWatcher", "0006_alter_fs_cache_tracking_lastscan"),
    ]

    operations = [
        migrations.AddField(
            model_name="fs_cache_tracking",
            name="invalidated",
            field=models.BooleanField(default=False),
        ),
    ]
