# Generated by Django 5.2.4 on 2025-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CacheWatcher", "0007_fs_cache_tracking_invalidated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fs_cache_tracking",
            name="lastscan",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddIndex(
            model_name="fs_cache_tracking",
            index=models.Index(
                fields=["directory_sha256", "invalidated"],
                name="CacheWatche_directo_d8cf09_idx",
            ),
        ),
    ]
