# Generated by Django 6.0a1 on 2025-10-06 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CacheWatcher", "0008_alter_fs_cache_tracking_lastscan_and_more"),
        ("quickbbs", "0031_indexdata_quickbbs_in_unique__5a24e6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fs_cache_tracking",
            name="directory",
            field=models.OneToOneField(
                blank=True,
                db_column="directory_data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Cache_Watcher",
                to="quickbbs.indexdirs",
                to_field="dir_fqpn_sha256",
            ),
        ),
    ]
