# Generated by Django 6.0a1 on 2025-10-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CacheWatcher", "0009_fs_cache_tracking_directory"),
        ("quickbbs", "0031_indexdata_quickbbs_in_unique__5a24e6_idx_and_more"),
    ]

    # Ordering hint only (no schema effect): this migration and 0009 reference
    # the pre-rename model name "quickbbs.indexdirs", so on a fresh database
    # they must replay before quickbbs 0035 renames it to DirectoryIndex.
    # Without this, CacheWatcher 0013's dependency on quickbbs 0041 lets the
    # planner run all quickbbs migrations first, and 0009's AddField fails
    # with "Related model 'quickbbs.indexdirs' cannot be resolved".
    run_before = [
        ("quickbbs", "0035_rename_indexdirs_to_directoryindex"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fs_cache_tracking",
            name="CacheWatche_directo_d8cf09_idx",
        ),
        migrations.AlterField(
            model_name="fs_cache_tracking",
            name="directory",
            field=models.OneToOneField(
                blank=True,
                db_column="directory_data",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Cache_Watcher",
                to="quickbbs.indexdirs",
                to_field="dir_fqpn_sha256",
            ),
        ),
        migrations.AlterField(
            model_name="fs_cache_tracking",
            name="invalidated",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="fs_cache_tracking",
            index=models.Index(fields=["directory", "invalidated"], name="CacheWatche_directo_4b46dc_idx"),
        ),
        migrations.RemoveField(
            model_name="fs_cache_tracking",
            name="DirName",
        ),
        migrations.RemoveField(
            model_name="fs_cache_tracking",
            name="directory_sha256",
        ),
    ]
