# Generated by Django 6.0.6 on 2026-07-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CacheWatcher", "0011_cachestatisticstracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fs_cache_tracking",
            name="invalidated",
            field=models.BooleanField(default=False),
        ),
    ]
