# Generated by Django 2.1.8 on 2019-04-29 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=None, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='filetypes',
            fields=[
                ('fileext', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('generic', models.BooleanField(db_index=True, default=False)),
                ('icon_filename', models.CharField(blank=True, db_index=True, default=None, max_length=384, null=True)),
                ('color', models.CharField(default='000000', max_length=7)),
                ('filetype', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('is_image', models.BooleanField(db_index=True, default=False)),
                ('is_archive', models.BooleanField(db_index=True, default=False)),
                ('is_pdf', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='index_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
                ('lastscan', models.FloatField(db_index=True)),
                ('lastmod', models.FloatField(db_index=True)),
                ('name', models.CharField(db_index=True, default=None, max_length=384)),
                ('sortname', models.CharField(db_index=True, default='', editable=False, max_length=384)),
                ('size', models.BigIntegerField(default=0)),
                ('numfiles', models.IntegerField(default=0)),
                ('numdirs', models.IntegerField(default=0)),
                ('count_subfiles', models.BigIntegerField(default=0)),
                ('fqpndirectory', models.CharField(db_index=True, default=0, max_length=384)),
                ('parent_dir_id', models.IntegerField(default=0)),
                ('is_dir', models.BooleanField(db_index=True, default=False)),
                ('is_pdf', models.BooleanField(db_index=True, default=False)),
                ('is_archive', models.BooleanField(db_index=True, default=False)),
                ('is_animated', models.BooleanField(db_index=True, default=False)),
                ('is_image', models.BooleanField(db_index=True, default=False)),
                ('ignore', models.BooleanField(db_index=True, default=False)),
                ('delete_pending', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Master Index',
                'verbose_name_plural': 'Master Index',
            },
        ),
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=None, editable=False, null=True)),
                ('ownerdetails', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ownership',
                'verbose_name_plural': 'Ownership',
            },
        ),
        migrations.CreateModel(
            name='Thumbnails_Archives',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
                ('zipfilepath', models.CharField(db_index=True, default=None, max_length=384, null=True)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=384)),
                ('FileName', models.CharField(db_index=True, default=None, max_length=384)),
                ('page', models.IntegerField(default=0)),
                ('FileSize', models.BigIntegerField(default=-1)),
                ('SmallThumb', models.BinaryField(default=b'')),
                ('MediumThumb', models.BinaryField(default=b'')),
                ('LargeThumb', models.BinaryField(default=b'')),
            ],
            options={
                'verbose_name': 'Archive Thumbnails Cache',
                'verbose_name_plural': 'Archive Thumbnails Cache',
            },
        ),
        migrations.CreateModel(
            name='Thumbnails_Dirs',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
                ('DirName', models.CharField(db_index=True, default=None, max_length=384, null=True)),
                ('FileSize', models.BigIntegerField(default=-1)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=384)),
                ('SmallThumb', models.BinaryField(default=b'')),
            ],
            options={
                'verbose_name': 'Directory Thumbnails Cache',
                'verbose_name_plural': 'Directory Thumbnails Cache',
            },
        ),
        migrations.CreateModel(
            name='Thumbnails_Files',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=384)),
                ('FileName', models.CharField(db_index=True, default=None, max_length=384)),
                ('FileSize', models.BigIntegerField(default=-1)),
                ('SmallThumb', models.BinaryField(default=b'')),
                ('MediumThumb', models.BinaryField(default=b'')),
                ('LargeThumb', models.BinaryField(default=b'')),
                ('is_pdf', models.BooleanField(db_index=True, default=False)),
                ('is_image', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Image File Thumbnails Cache',
                'verbose_name_plural': 'Image File Thumbnails Cache',
            },
        ),
        migrations.AddField(
            model_name='index_data',
            name='archives',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.Thumbnails_Archives'),
        ),
        migrations.AddField(
            model_name='index_data',
            name='directory',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.Thumbnails_Dirs'),
        ),
        migrations.AddField(
            model_name='index_data',
            name='file_tnail',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.Thumbnails_Files'),
        ),
        migrations.AddField(
            model_name='index_data',
            name='filetype',
            field=models.ForeignKey(default='.none', on_delete=django.db.models.deletion.CASCADE, to='quickbbs.filetypes'),
        ),
        migrations.AddField(
            model_name='index_data',
            name='ownership',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.owners'),
        ),
    ]
