# Generated by Django 3.0.4 on 2020-04-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0002_filetypes_is_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_data',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='index_data',
            name='is_dir',
        ),
        migrations.RemoveField(
            model_name='index_data',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='index_data',
            name='is_pdf',
        ),
    ]
