# Generated by Django 3.0.5 on 2020-04-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0003_auto_20200428_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetypes',
            name='is_dir',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
