# Generated by Django 3.0.5 on 2020-04-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0004_filetypes_is_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnails_files',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='thumbnails_files',
            name='is_pdf',
        ),
    ]
