# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-23 22:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    #replaces = [(b'quickbbs', '0001_squashed_0019_auto_20171108_0155'), (b'quickbbs', '0002_indexdata_is_image'), (b'quickbbs', '0003_auto_20180104_0041'), (b'quickbbs', '0004_auto_20180104_0043'), (b'quickbbs', '0005_auto_20180105_2126'), (b'quickbbs', '0006_indexdata_md5_hash_id'), (b'quickbbs', '0007_auto_20180309_0637'), (b'quickbbs', '0008_remove_indexdata_md5_hash_id'), (b'quickbbs', '0009_indexdata_thumbnail_id'), (b'quickbbs', '0010_auto_20180311_1641'), (b'quickbbs', '0011_thumbnails_files_filename'), (b'quickbbs', '0012_auto_20180314_1134'), (b'quickbbs', '0013_auto_20180315_0956'), (b'quickbbs', '0014_thumbnails_files_filesize'), (b'quickbbs', '0015_delete_thumbnails_files'), (b'quickbbs', '0016_thumbnails_files'), (b'quickbbs', '0017_auto_20180315_2138'), (b'quickbbs', '0018_auto_20180315_2147'), (b'quickbbs', '0019_thumbnails_dirs'), (b'quickbbs', '0020_auto_20180317_1303'), (b'quickbbs', '0021_thumbnails_dirs_filesize'), (b'quickbbs', '0022_auto_20180330_0146'), (b'quickbbs', '0023_thumbnails_archives_page'), (b'quickbbs', '0024_auto_20180407_0225'), (b'quickbbs', '0025_auto_20180407_0233'), (b'quickbbs', '0026_auto_20180408_1605'), (b'quickbbs', '0027_auto_20180415_0301'), (b'quickbbs', '0028_auto_20180417_0220'), (b'quickbbs', '0029_auto_20180417_0223'), (b'quickbbs', '0030_auto_20180418_0024'), (b'quickbbs', '0031_thumbnails_archives_zipfilepath'), (b'quickbbs', '0032_owners'), (b'quickbbs', '0033_auto_20180425_1121'), (b'quickbbs', '0034_index_data_ownership'), (b'quickbbs', '0035_index_data_directory'), (b'quickbbs', '0036_index_data_file_tnail'), (b'quickbbs', '0037_index_data_archives'), (b'quickbbs', '0038_thumbnails_dirs_dirname'), (b'quickbbs', '0039_auto_20180512_0214'), (b'quickbbs', '0040_filetypes')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=None, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnails_Archives',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('SmallThumb', models.BinaryField(default=b'')),
                ('MediumThumb', models.BinaryField(default=b'')),
                ('LargeThumb', models.BinaryField(default=b'')),
                ('FileName', models.CharField(db_index=True, default=None, max_length=512)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileSize', models.BigIntegerField(default=-1)),
                ('page', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
                ('zipfilepath', models.CharField(db_index=True, default=None, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnails_Files',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileName', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileSize', models.BigIntegerField(default=-1)),
                ('SmallThumb', models.BinaryField(default=b'')),
                ('MediumThumb', models.BinaryField(default=b'')),
                ('LargeThumb', models.BinaryField(default=b'')),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
                ('is_image', models.BooleanField(db_index=True, default=False)),
                ('is_pdf', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnails_Dirs',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=512)),
                ('SmallThumb', models.BinaryField(default=b'')),
                ('FileSize', models.BigIntegerField(default=-1)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
                ('DirName', models.CharField(db_index=True, default=None, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='index_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastscan', models.FloatField(db_index=True)),
                ('lastmod', models.FloatField(db_index=True)),
                ('name', models.CharField(db_index=True, default=None, max_length=512)),
                ('sortname', models.CharField(db_index=True, default='', editable=False, max_length=512)),
                ('size', models.BigIntegerField(default=0)),
                ('numfiles', models.IntegerField(default=0)),
                ('numdirs', models.IntegerField(default=0)),
                ('fqpndirectory', models.CharField(db_index=True, default=0, max_length=512)),
                ('parent_dir_id', models.IntegerField(default=0)),
                ('is_dir', models.BooleanField(db_index=True, default=False)),
                ('is_pdf', models.BooleanField(db_index=True, default=False)),
                ('is_archive', models.BooleanField(db_index=True, default=False)),
                ('is_image', models.BooleanField(db_index=True, default=False)),
                ('ignore', models.BooleanField(db_index=True, default=False)),
                ('delete_pending', models.BooleanField(db_index=True, default=False)),
                ('uuid', models.UUIDField(db_index=True, default=None, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=None, editable=False, null=True)),
                ('ownerdetails', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='index_data',
            name='ownership',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.owners'),
        ),
        migrations.AddField(
            model_name='index_data',
            name='directory',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.Thumbnails_Dirs'),
        ),
        migrations.AddField(
            model_name='index_data',
            name='file_tnail',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.Thumbnails_Files'),
        ),
        migrations.AddField(
            model_name='index_data',
            name='archives',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickbbs.Thumbnails_Archives'),
        ),
        migrations.CreateModel(
            name='filetypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileext', models.CharField(db_index=True, max_length=10, unique=True)),
                ('filesize', models.BigIntegerField(default=-1)),
                ('filename', models.CharField(db_index=True, default=None, max_length=512)),
                ('htmlcolor', models.CharField(max_length=7)),
                ('imageformat', models.BooleanField(db_index=True, default=False)),
                ('textformat', models.BooleanField(db_index=True, default=False)),
                ('smallthumb', models.BinaryField(default=b'')),
                ('largethumb', models.BinaryField(default=b'')),
                ('use_generic_icon',models.BooleanField(db_index=True, default=False))
            ],
        ),
    ]
