# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0005_auto_20171103_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dirdata',
            old_name='DirFQPN',
            new_name='DirPN',
        ),
        migrations.AddField(
            model_name='filedata',
            name='LastScan',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dirdata',
            name='LastMod',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dirdata',
            name='LastScan',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='LastMod',
            field=models.DateTimeField(db_index=True),
        ),
    ]
