# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0006_auto_20171104_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dirdata',
            name='LastScan',
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='LastScan',
        ),
    ]
