# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0009_auto_20171104_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='LastScan',
            field=models.DateTimeField(db_index=True),
        ),
    ]
