# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0011_auto_20171105_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirdata',
            name='LastMod',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dirdata',
            name='LastScan',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='LastMod',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='LastScan',
            field=models.FloatField(db_index=True),
        ),
    ]
