# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0012_auto_20171107_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='FQPNDirectory',
            field=models.CharField(db_index=True, default=0, max_length=512),
        ),
    ]
