# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0001_squashed_0019_auto_20171108_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdata',
            name='is_image',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
