# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0004_auto_20180104_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnails',
            fields=[
                ('md5_hash_id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('SmallThumb', models.BinaryField()),
                ('MediumThumb', models.BinaryField()),
                ('LargeThumb', models.BinaryField()),
                ('UsageCount', models.IntegerField(default=0)),
                ('DeletePending', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='indexdata',
            name='LargeThumb',
        ),
        migrations.RemoveField(
            model_name='indexdata',
            name='MediumThumb',
        ),
        migrations.RemoveField(
            model_name='indexdata',
            name='SmallThumb',
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='DeletePending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='Ignore',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
