# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0006_indexdata_md5_hash_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnails_Archives',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('SmallThumb', models.BinaryField()),
                ('MediumThumb', models.BinaryField()),
                ('LargeThumb', models.BinaryField()),
                ('UsageCount', models.IntegerField(default=0)),
                ('DeletePending', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnails_Files',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('SmallThumb', models.BinaryField()),
                ('MediumThumb', models.BinaryField()),
                ('LargeThumb', models.BinaryField()),
                ('UsageCount', models.IntegerField(default=0)),
                ('DeletePending', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Thumbnails',
        ),
    ]
