# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0008_remove_indexdata_md5_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdata',
            name='Thumbnail_ID',
            field=models.IntegerField(default=0),
        ),
    ]
