# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0009_indexdata_thumbnail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails_archives',
            name='Flag_For_Regeneration',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='thumbnails_files',
            name='Flag_For_Regeneration',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
