# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0010_auto_20180311_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails_files',
            name='FileName',
            field=models.CharField(db_index=True, default=None, max_length=512),
        ),
    ]
