# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0011_thumbnails_files_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdata',
            name='Thumbnail_ID',
        ),
        migrations.RemoveField(
            model_name='thumbnails_files',
            name='UsageCount',
        ),
        migrations.AddField(
            model_name='thumbnails_files',
            name='FilePath',
            field=models.CharField(db_index=True, default=None, max_length=512),
        ),
    ]
