# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0013_auto_20180315_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails_files',
            name='FileSize',
            field=models.IntegerField(default=-1),
        ),
    ]
