# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0014_thumbnails_files_filesize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnails_Files',
        ),
    ]
