# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0015_delete_thumbnails_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnails_Files',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileName', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileSize', models.IntegerField(default=-1)),
                ('SmallThumb', models.BinaryField(default=None)),
                ('MediumThumb', models.BinaryField(default=None)),
                ('LargeThumb', models.BinaryField(default=None)),
                ('Flag_For_Regeneration', models.BooleanField(db_index=True, default=True)),
                ('DeletePending', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
