# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0018_auto_20180315_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnails_Dirs',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('FilePath', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileName', models.CharField(db_index=True, default=None, max_length=512)),
                ('FileSize', models.IntegerField(default=-1)),
                ('SmallThumb', models.BinaryField(default=b'')),
            ],
        ),
    ]
