# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0019_thumbnails_dirs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnails_dirs',
            name='FileName',
        ),
        migrations.RemoveField(
            model_name='thumbnails_dirs',
            name='FileSize',
        ),
    ]
