# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0020_auto_20180317_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails_dirs',
            name='FileSize',
            field=models.IntegerField(default=-1),
        ),
    ]
