# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0022_auto_20180330_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails_archives',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
