# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0023_thumbnails_archives_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastScan', models.FloatField(db_index=True)),
                ('lastMod', models.FloatField(db_index=True)),
                ('name', models.CharField(db_index=True, default=None, max_length=512)),
                ('sortname', models.CharField(db_index=True, default='', editable=False, max_length=512)),
                ('size', models.IntegerField(default=0)),
                ('numfiles', models.IntegerField(default=0)),
                ('numdirs', models.IntegerField(default=0)),
                ('fqpndirectory', models.CharField(db_index=True, default=0, max_length=512)),
                ('parent_dir_id', models.IntegerField(default=0)),
                ('is_dir', models.BooleanField(db_index=True, default=False)),
                ('is_pdf', models.BooleanField(db_index=True, default=False)),
                ('is_archive', models.BooleanField(db_index=True, default=False)),
                ('is_image', models.BooleanField(db_index=True, default=False)),
                ('ignore', models.BooleanField(db_index=True, default=False)),
                ('delete_pending', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='IndexData',
        ),
    ]
