# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0024_auto_20180407_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index_data',
            old_name='lastMod',
            new_name='lastmod',
        ),
        migrations.RenameField(
            model_name='index_data',
            old_name='lastScan',
            new_name='lastscan',
        ),
    ]
