# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0025_auto_20180407_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_data',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thumbnails_archives',
            name='FileSize',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='thumbnails_dirs',
            name='FileSize',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='thumbnails_files',
            name='FileSize',
            field=models.BigIntegerField(default=-1),
        ),
    ]
