# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direntry',
            old_name='DirFQFN',
            new_name='DirFQPN',
        ),
        migrations.RenameField(
            model_name='fileentry',
            old_name='FilenameName',
            new_name='FileName',
        ),
        migrations.RemoveField(
            model_name='direntry',
            name='ThumbURL',
        ),
        migrations.RemoveField(
            model_name='fileentry',
            name='LastScan',
        ),
        migrations.RemoveField(
            model_name='fileentry',
            name='NumDirs',
        ),
        migrations.RemoveField(
            model_name='fileentry',
            name='ThumbFQFN',
        ),
        migrations.RemoveField(
            model_name='fileentry',
            name='ThumbURL',
        ),
        migrations.AddField(
            model_name='fileentry',
            name='FQPNParentDir',
            field=models.IntegerField(default=0),
        ),
    ]
