# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0002_auto_20171102_0127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirEntry',
            new_name='DirData',
        ),
        migrations.RenameModel(
            old_name='FileEntry',
            new_name='FileData',
        ),
    ]
