# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0003_auto_20171102_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='is_archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='filedata',
            name='is_pdf',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='DeletePending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='IgnoreFile',
            field=models.BooleanField(default=False),
        ),
    ]
