# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0004_auto_20171102_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedata',
            old_name='FQPNParentDir',
            new_name='FQPNDirectory',
        ),
        migrations.RenameField(
            model_name='filedata',
            old_name='IgnoreFile',
            new_name='Ignore',
        ),
    ]
