# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0007_auto_20171104_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirdata',
            name='LastScan',
            field=models.DateTimeField(db_index=True, default=b'2017-11-04 01:37:59'),
        ),
        migrations.AddField(
            model_name='filedata',
            name='LastScan',
            field=models.DateTimeField(db_index=True, default=b'2017-11-04 01:37:59'),
        ),
    ]
