# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0010_auto_20171104_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirdata',
            name='LastMod',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dirdata',
            name='LastScan',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='LastMod',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='LastScan',
            field=models.IntegerField(db_index=True),
        ),
    ]
