# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbbs', '0018_auto_20171108_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdata',
            name='NumDirs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexdata',
            name='NumFiles',
            field=models.IntegerField(default=0),
        ),
    ]
