pip uninstall  directory_caching
pip uninstall  jinja
pip uninstall  markdown
pip uninstall  natsort
pip uninstall  passlib
pip uninstall  Pillow
pip uninstall  pybonjour
pip uninstall  rarfile
pip uninstall  rarfile
pip uninstall  semantic_url
pip uninstall  scandir
pip uninstall  twisted
pip uninstall  txbonjour
pip uninstall  unidecode
