pip3 uninstall  directory_caching
pip3 uninstall  jinja
pip3 uninstall  markdown
pip3 uninstall  naturalsort
pip3 uninstall  passlib
pip3 uninstall  Pillow
pip3 uninstall  pybonjour
pip3 uninstall  rarfile
pip3 uninstall  rarfile
pip3 uninstall  semantic_url
pip3 uninstall  scandir
pip3 uninstall  twisted
pip3 uninstall  txbonjour
pip3 uninstall  unidecode
pip3 uninstall  fastnumbers
pip3 uninstall  natsort
pip3 uninstall  django-bootstrap3
pip3 uninstall  python-thumbnails
pip3 uninstall  django-allauth
pip3 uninstall  django-debug-toolbar
pip3 uninstall  django-jinja
pip3 uninstall  pathlib2
pip3 uninstall  configparser
pip3 uninstall  psycopg2
pip3 uninstall  psycopg2-binary #psycopg2
pip3 uninstall  PyMuPDF
