#pip3 install --upgrade directory_caching
pip3 install --upgrade jinja
pip3 install --upgrade markdown
pip3 install --upgrade naturalsort
pip3 install --upgrade passlib
pip3 install --upgrade Pillow
pip3 install --upgrade pybonjour
pip3 install --upgrade rarfile
pip3 install --upgrade scandir
pip3 install --upgrade semantic_url
pip3 install --upgrade twisted
pip3 install --upgrade txbonjour
pip3 install --upgrade unidecode
pip3 install --upgrade fastnumbers
pip3 install --upgrade natsort
pip3 install --upgrade django-bootstrap3
pip3 install --upgrade python-thumbnails
pip3 install --upgrade django-allauth
pip3 install --upgrade django-debug-toolbar
pip3 install --upgrade django-jinja
pip3 install --upgrade pathlib2
pip3 install --upgrade configparser
pip3 install --upgrade psycopg2
pip3 install --upgrade psycopg2-binary #psycopg2
pip3 install --upgrade PyMuPDF
