#pip install --upgrade directory_caching
pip install --upgrade jinja
pip install --upgrade markdown
pip install --upgrade naturalsort
pip install --upgrade passlib
pip install --upgrade Pillow
pip install --upgrade pybonjour
pip install --upgrade rarfile
pip install --upgrade scandir
pip install --upgrade semantic_url
#pip install --upgrade twisted
pip install --upgrade txbonjour
pip install --upgrade unidecode
pip install --upgrade fastnumbers
pip install --upgrade natsort
pip install --upgrade django-bootstrap3
pip install --upgrade python-thumbnails
pip install --upgrade django-allauth
pip install --upgrade django-debug-toolbar
pip install --upgrade django-jinja
pip install --upgrade django-jinja
pip install --upgrade pathlib2
pip install --upgrade configparser
pip install --upgrade psycopg2-binary #psycopg2
pip install --upgrade PyMuPDF
