pip install --upgrade directory_caching
pip install --upgrade jinja
pip install --upgrade markdown
pip install --upgrade natsort
pip install --upgrade passlib
pip install --upgrade Pillow
pip install --upgrade pybonjour
pip install --upgrade rarfile
pip install --upgrade rarfile
pip install --upgrade scandir
pip install --upgrade twisted
pip install --upgrade txbonjour
pip install --upgrade unidecode
