# Generated by Django 5.2.3 on 2025-06-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filetypes",
            name="thumbnail",
            field=models.BinaryField(default=b"", null=True),
        ),
    ]
