# Generated by Django 4.1.3 on 2022-11-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filetypes",
            name="is_audio",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
