# Generated by Django 6.0b1 on 2025-11-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0002_filetypes_thumbnail"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="filetypes",
            index=models.Index(fields=["is_image", "is_movie", "is_pdf"], name="filetypes_thumbnailable_idx"),
        ),
        migrations.AddIndex(
            model_name="filetypes",
            index=models.Index(fields=["is_dir", "is_link"], name="filetypes_dir_link_idx"),
        ),
        migrations.AddIndex(
            model_name="filetypes",
            index=models.Index(fields=["is_text", "is_html", "is_markdown"], name="filetypes_text_idx"),
        ),
    ]
