# Generated by Django 6.0.1 on 2026-01-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetypes", "0003_filetypes_filetypes_thumbnailable_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filetypes",
            name="filetype",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="generic",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="icon_filename",
            field=models.CharField(blank=True, default="", max_length=384),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_audio",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_dir",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_html",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_markdown",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_movie",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_pdf",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filetypes",
            name="is_text",
            field=models.BooleanField(default=False),
        ),
    ]
