# Generated by Django 6.1 on 2026-08-16 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("compiled_json", models.JSONField()),
                ("ink_version", models.CharField(blank=True, max_length=32)),
                ("is_public", models.BooleanField(default=False)),
                ("source_fqfn", models.CharField(blank=True, default="", max_length=1024)),
                ("source_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="if_stories", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Stories",
            },
        ),
        migrations.CreateModel(
            name="StoryImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag_name", models.CharField(db_index=True, max_length=255)),
                ("story", models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="images", to="interactive_fiction.story")),
            ],
        ),
        migrations.AddField(
            model_name="story",
            name="cover_image",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name="+", to="interactive_fiction.storyimage"
            ),
        ),
        migrations.CreateModel(
            name="StoryAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("story", models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="grants", to="interactive_fiction.story")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="if_story_grants", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("story", "user"), name="unique_story_user_grant")],
            },
        ),
        migrations.AddConstraint(
            model_name="storyimage",
            constraint=models.UniqueConstraint(fields=("story", "tag_name"), name="unique_story_image_tag"),
        ),
    ]
