# Generated by Django 6.1 on 2026-08-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentGame",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.JSONField()),
                ("turn_count", models.IntegerField(default=-1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "story",
                    models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="current_games", to="interactive_fiction.story"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="if_current_games", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("user", "story"), name="unique_user_story_current")],
            },
        ),
        migrations.CreateModel(
            name="SaveState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slot", models.PositiveSmallIntegerField()),
                ("label", models.CharField(blank=True, max_length=100)),
                ("state", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("story", models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="saves", to="interactive_fiction.story")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="if_saves", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "story", "slot"), name="unique_user_story_slot"),
                    models.CheckConstraint(condition=models.Q(("slot__lt", 32)), name="savestate_slot_ceiling"),
                ],
            },
        ),
    ]
