# Generated by Django 6.1 on 2026-08-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0002_currentgame_savestate"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryImageBlob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sha256_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("content_type", models.CharField(max_length=100)),
                ("image_blob", models.BinaryField()),
                ("cover_thumb", models.BinaryField(blank=True, default=None, null=True)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="story",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="storyimage",
            name="blob_id",
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storyimage",
            name="is_cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="storyimage",
            constraint=models.UniqueConstraint(condition=models.Q(("is_cover", True)), fields=("story",), name="unique_story_cover_image"),
        ),
    ]
