# Generated by Django 6.1 on 2026-08-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0006_delete_storyimageblob_remove_storyimage_blob_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="is_engine_trusted",
            field=models.BooleanField(default=False),
        ),
    ]
