# Generated by Django 6.1 on 2026-08-22 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0007_story_is_engine_trusted"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorySystemConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("system_name", models.CharField(choices=[("location_graph", "Location graph")], max_length=64)),
                ("config", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "story",
                    models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name="system_configs", to="interactive_fiction.story"),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("story", "system_name"), name="unique_story_system_config")],
            },
        ),
    ]
