# Generated by Django 6.1 on 2026-08-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0008_storysystemconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storysystemconfig",
            name="system_name",
            field=models.CharField(choices=[("location_graph", "Location graph"), ("character_occupancy", "Character occupancy")], max_length=64),
        ),
    ]
