# Generated by Django 6.1 on 2026-08-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0009_alter_storysystemconfig_system_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineAPI",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                ("is_enabled", models.BooleanField(default=False)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Engine APIs",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="storysystemconfig",
            name="system_name",
            field=models.CharField(max_length=64),
        ),
    ]
