# Generated by Django 6.1 on 2026-08-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0010_engineapi_alter_storysystemconfig_system_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storysystemconfig",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
