# Generated by Django 6.1 on 2026-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0011_alter_storysystemconfig_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="game_author",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="story",
            name="game_ingestion_error",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="story",
            name="game_required_plugins",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
