# Generated by Django 6.1 on 2026-08-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0012_story_game_author_story_game_ingestion_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="game_new_game_fields",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
