# Generated by Django 6.1 on 2026-09-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0013_story_game_new_game_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="bundle_directory_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="story",
            name="bundle_manifest_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="story",
            name="bundle_story_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="story",
            name="game_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
