# Generated by Django 6.1 on 2026-09-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0014_story_bundle_directory_sha256_and_more"),
        ("thumbnails", "0007_remove_thumbnailfiles_thumbnails_sha256_lookup_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="storyimage",
            name="unique_story_image_tag",
        ),
        migrations.RemoveConstraint(
            model_name="storyimage",
            name="unique_story_cover_image",
        ),
        migrations.AddField(
            model_name="story",
            name="cover_thumbnail",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name="if_story_covers", to="thumbnails.thumbnailfiles"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="main_story_member",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.DeleteModel(
            name="StoryImage",
        ),
    ]
