# Generated by Django 6.1 on 2026-09-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_fiction", "0015_remove_storyimage_unique_story_image_tag_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="storysystemconfig",
            name="unique_story_system_config",
        ),
        migrations.DeleteModel(
            name="StorySystemConfig",
        ),
    ]
